[package]
org = "wso2"
name = "rag_ingestion"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="azure.ai.search"
version="1.0.0"
repository="local"
